name: KarolWilliams
favicon: null
layout_spectrum: 0.53712
typography_spectrum: 0.3445184580050409
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#edbf2b'
    - '#ef832b'
    - '#779f97'
    - '#00007f'
    - '#5b6958'
  brandStrength: 0.25
  lightness: 0.7609305768273771
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
